// This file is auto-generated by @hey-api/openapi-ts

export type GetFinalStateResponse = {
    gameId?: (string) | null;
    grid?: Grid;
    stepCount?: number;
    loopDetectStep?: (number) | null;
    errorMessage?: (string) | null;
};

export type Grid = {
    width?: number;
    height?: number;
    packedData?: (string) | null;
    intArrayData?: Array<Array<(number)>> | null;
};

export type SavedGame = {
    id?: (string) | null;
    grid?: Grid;
};

export type PostGameCreateData = {
    body?: Grid;
};

export type PostGameCreateResponse = (string);

export type PostGameCreateError = unknown;

export type GetGameListResponse = (Array<(string)>);

export type GetGameListError = unknown;

export type GetGameLoadData = {
    query?: {
        gameId?: string;
        includeIntArray?: boolean;
    };
};

export type GetGameLoadResponse = (SavedGame);

export type GetGameLoadError = unknown;

export type GetGameFinalStateData = {
    query?: {
        gameId?: string;
        includeIntArray?: boolean;
        locateMatchOnLoop?: boolean;
        maxSteps?: number;
    };
};

export type GetGameFinalStateResponse = (GetFinalStateResponse);

export type GetGameFinalStateError = unknown;

export type GetGridCreateBitArrayData = {
    query?: {
        height?: number;
        seed?: number;
        width?: number;
    };
};

export type GetGridCreateBitArrayResponse = (Array<Array<(number)>>);

export type GetGridCreateBitArrayError = unknown;

export type GetGridCreatePackedData = {
    query?: {
        height?: number;
        seed?: number;
        width?: number;
    };
};

export type GetGridCreatePackedResponse = (string);

export type GetGridCreatePackedError = unknown;

export type PostGridGenerateNextData = {
    body?: Grid;
};

export type PostGridGenerateNextResponse = (Grid);

export type PostGridGenerateNextError = unknown;